import type { ReactNode } from "react";
import { Link, useNavigate } from "@tanstack/react-router";
import { Bell, LayoutDashboard, LogOut, Map, Menu, Settings, ShieldCheck, UserRound, FilePlus2, Files, ClipboardCheck } from "lucide-react";
import { useState } from "react";
import { supabase } from "@/integrations/supabase/client";
import { Brand } from "./brand";
import { Button } from "@/components/ui/button";

const roleLinks = {
 user:[{to:"/dashboard",label:"Dashboard",icon:LayoutDashboard},{to:"/report",label:"Report Incident",icon:FilePlus2},{to:"/dashboard",label:"My Reports",icon:Files},{to:"/safety-map",label:"Safety Map",icon:Map},{to:"/dashboard",label:"Notifications",icon:Bell},{to:"/dashboard",label:"Profile",icon:UserRound}],
 officer:[{to:"/officer",label:"Overview",icon:LayoutDashboard},{to:"/officer",label:"All Incidents",icon:Files},{to:"/safety-map",label:"Incident Map",icon:Map},{to:"/officer",label:"Review Queue",icon:ClipboardCheck},{to:"/officer",label:"Reports",icon:ShieldCheck},{to:"/officer",label:"Settings",icon:Settings}],
 principal:[{to:"/principal",label:"Institution Overview",icon:LayoutDashboard},{to:"/principal",label:"College Reports",icon:Files},{to:"/safety-map",label:"Authorized Map",icon:Map},{to:"/principal",label:"Review Queue",icon:ClipboardCheck},{to:"/principal",label:"Settings",icon:Settings}],
} as const;

export function DashboardShell({role,title,subtitle,children}:{role:keyof typeof roleLinks;title:string;subtitle:string;children:ReactNode}) { const [open,setOpen]=useState(false); const navigate=useNavigate(); async function logout(){await supabase.auth.signOut();navigate({to:"/auth",search:{mode:"login"},replace:true});} return <div className="min-h-screen bg-background"><aside className={`fixed inset-y-0 left-0 z-50 w-72 border-r border-border bg-panel-strong p-5 transition-transform lg:translate-x-0 ${open?"translate-x-0":"-translate-x-full"}`}><div className="mb-10"><Brand/></div><nav className="grid gap-1">{roleLinks[role].map((item,i)=>{const Icon=item.icon;return <Link key={`${item.label}-${i}`} to={item.to} onClick={()=>setOpen(false)} className="flex items-center gap-3 rounded-lg px-3 py-3 text-sm font-semibold text-muted-foreground hover:bg-accent hover:text-foreground" activeProps={{className:"bg-primary/15 text-primary"}}><Icon className="size-5"/>{item.label}</Link>})}</nav><Button variant="ghost" className="absolute bottom-5 left-5 right-5 justify-start text-muted-foreground" onClick={logout}><LogOut/>Logout</Button></aside><div className="lg:pl-72"><header className="sticky top-0 z-40 grid grid-cols-[auto_minmax(0,1fr)_auto] items-center gap-3 border-b border-border bg-background/90 px-4 py-4 backdrop-blur sm:px-6"><Button variant="ghost" size="icon" className="lg:hidden" onClick={()=>setOpen(v=>!v)} aria-label="Open navigation"><Menu/></Button><div className="min-w-0"><h1 className="truncate text-xl font-bold">{title}</h1><p className="truncate text-xs text-muted-foreground sm:text-sm">{subtitle}</p></div><div className="grid size-10 place-items-center rounded-full bg-primary/15 text-sm font-bold text-primary">CC</div></header><main className="p-4 sm:p-6 lg:p-8">{children}</main></div>{open&&<button className="fixed inset-0 z-40 bg-background/70 lg:hidden" onClick={()=>setOpen(false)} aria-label="Close navigation"/>}</div>; }